### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by jelabarre59** [pratikpatel8982/yt-dlp-hianime#3]
What does this plugin use as a "package name" (as per the directions at https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installing-plugins.  I tried putting the hianime.py file into  ~/yt-dlp/plugins/yt-dlp-hianime/yt_dlp_plugins/extractor/ but yt-dlp still wouldn;t recognize a hianime.to URL.

**Comment by pratikpatel8982** [comment]
What OS are you using?
The package name can be anything, but I use yt-dlp-hianime.

**Comment by jelabarre59** [comment]
With the plugin at  ~/yt-dlp/plugins/yt-dlp-hianime/yt_dlp_plugins/extractor/hianime.py it still fails:


```
~$ yt-dlp -v https://hianime.to/watch/my-otome-2304?ep=82595&ep=82595
[1] 1215425
jelabarre@b450a-lx:~$ [debug] Command-line config: ['-v', 'https://hianime.to/watch/my-otome-2304?ep=82595']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.10.4-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (fdk,setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1830 extractors
[generic] Extracting URL: https://hianime.to/watch/my-otome-2304?ep=82595
[generic] my-otome-2304?ep=82595: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] my-otome-2304?ep=82595: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://hianime.to/watch/my-otome-2304?ep=82595
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://hianime.to/watch/my-otome-2304?ep=82595
```

Tried with some other randomly selected titles as well.  All fail the same way.

**Comment by pratikpatel8982** [comment]
The extractor is not properly installed. It's not being detected. Make sure that the folder 
yt-dlp/plugins/yt-dlp-hianime/yt_dlp_plugins/extractor/hianime.py

Is in the same location as yt-dlp.exe. I can provide a yt-dlp.exe with built in plugin if you want.

**Comment by jelabarre59** [comment]
A MSWin executable won't do me much good on Linux <g>.

**Comment by pratikpatel8982** [comment]
If you are using pip, You can install the plugin by using this command.

`python -m pip install -U https://github.com/pratikpatel8982/yt-dlp-hianime/archive/master.zip`

**Comment by jelabarre59** [comment]
Tried installing with the pip command above (both as my regular user, as well as with sudo) and it still fails

~$ yt-dlp https://hianime.to/watch/shamanic-princess-5152
```
[generic] Extracting URL: https://hianime.to/watch/shamanic-princess-5152
[generic] shamanic-princess-5152: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] shamanic-princess-5152: Extracting information
ERROR: Unsupported URL: https://hianime.to/watch/shamanic-princess-5152

```

**Comment by jelabarre59** [comment]
I had to clear out ALL copies of yt-dlp and do a fresh pip install yt-dlp first.

**Comment by pratikpatel8982** [comment]
Does it work now???

**Comment by jelabarre59** [comment]
It's pulling videos down now.  Granted, some are having download errors, but I think that's more down to the server itself.
