### ISSUE TITLE
Cannot download anymore

### ISSUE THREAD

**Issue by Spiggie** [pratikpatel8982/yt-dlp-hianime#7]
Yesterday I could download episodes via playlist, today it is not working anymore. I don't know if HiAnime changed something or what else has happened.

I am using this code to download the playlist:
```
options = {
    'outtmpl': '%(series)s\\E%(episode_number)03d - %(title)s.%(ext)s',
    'writeautomaticsub': True,
    'writesubtitles': True
}

with YoutubeDL(options) as ydl:
    ydl.download('https://hianime.to/watch/one-piece-100')

[HiAnime] Extracting URL: https://hianime.to/watch/one-piece-100
[HiAnime] 100: Fetching Anime Title
[HiAnime] 100: Fetching Episode List
[download] Downloading playlist: One Piece
[HiAnime] Playlist One Piece: Downloading 1117 items of 1117
[download] Downloading item 1 of 1117
ERROR: No suitable extractor (HiAnime) found for URL https://hianime.tojavascript:;
---------------------------------------------------------------------------
DownloadError                             Traceback (most recent call last)
Cell In[13], line 8
      1 options = {
      2     'outtmpl': '%(series)s\\E%(episode_number)03d - %(title)s.%(ext)s',
      3     'writeautomaticsub': True,
      4     'writesubtitles': True
      5 }
      7 with YoutubeDL(options) as ydl:
----> 8     ydl.download('https://hianime.to/watch/one-piece-100')
      9     #ydl.download('https://hianime.to/watch/one-piece-100?ep=2142')

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:3607, in YoutubeDL.download(self, url_list)
   3604     raise SameFileError(outtmpl)
   3606 for url in url_list:
-> 3607     self.__download_wrapper(self.extract_info)(
   3608         url, force_generic_extractor=self.params.get('force_generic_extractor', False))
   3610 return self._download_retcode

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:3582, in YoutubeDL.__download_wrapper.<locals>.wrapper(*args, **kwargs)
   3579 @functools.wraps(func)
   3580 def wrapper(*args, **kwargs):
   3581     try:
-> 3582         res = func(*args, **kwargs)
   3583     except UnavailableVideoError as e:
   3584         self.report_error(e)

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1615, in YoutubeDL.extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
   1613             raise ExistingVideoReached
   1614         break
-> 1615     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
   1616 else:
   1617     extractors_restricted = self.params.get('allowed_extractors') not in (None, ['default'])

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1626, in YoutubeDL._handle_extraction_exceptions.<locals>.wrapper(self, *args, **kwargs)
   1624 while True:
   1625     try:
-> 1626         return func(self, *args, **kwargs)
   1627     except (DownloadCancelled, LazyList.IndexError, PagedList.IndexError):
   1628         raise

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1782, in YoutubeDL.__extract_info(self, url, ie, download, extra_info, process)
   1780 if process:
   1781     self._wait_for_video(ie_result)
-> 1782     return self.process_ie_result(ie_result, download, extra_info)
   1783 else:
   1784     return ie_result

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1911, in YoutubeDL.process_ie_result(self, ie_result, download, extra_info)
   1909 self._sanitize_thumbnails(ie_result)
   1910 try:
-> 1911     return self.__process_playlist(ie_result, download)
   1912 finally:
   1913     self._playlist_level -= 1

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:2058, in YoutubeDL.__process_playlist(self, ie_result, download)
   2052     continue
   2054 self.to_screen(
   2055     f'[download] Downloading item {self._format_screen(i + 1, self.Styles.ID)} '
   2056     f'of {self._format_screen(n_entries, self.Styles.EMPHASIS)}')
-> 2058 entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
   2059     'playlist_index': playlist_index,
   2060     'playlist_autonumber': i + 1,
   2061 }, extra))
   2062 if not entry_result:
   2063     failures += 1

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1626, in YoutubeDL._handle_extraction_exceptions.<locals>.wrapper(self, *args, **kwargs)
   1624 while True:
   1625     try:
-> 1626         return func(self, *args, **kwargs)
   1627     except (DownloadCancelled, LazyList.IndexError, PagedList.IndexError):
   1628         raise

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:2090, in YoutubeDL.__process_iterable_entry(self, entry, download, extra_info)
   2088 @_handle_extraction_exceptions
   2089 def __process_iterable_entry(self, entry, download, extra_info):
-> 2090     return self.process_ie_result(
   2091         entry, download=download, extra_info=extra_info)

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1861, in YoutubeDL.process_ie_result(self, ie_result, download, extra_info)
   1857     return ie_result
   1858 elif result_type == 'url':
   1859     # We have to add extra_info to the results because it may be
   1860     # contained in a playlist
-> 1861     return self.extract_info(
   1862         ie_result['url'], download,
   1863         ie_key=ie_result.get('ie_key'),
   1864         extra_info=extra_info)
   1865 elif result_type == 'url_transparent':
   1866     # Use the information from the embedding page
   1867     info = self.extract_info(
   1868         ie_result['url'], ie_key=ie_result.get('ie_key'),
   1869         extra_info=extra_info, download=False, process=False)

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1618, in YoutubeDL.extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
   1616 else:
   1617     extractors_restricted = self.params.get('allowed_extractors') not in (None, ['default'])
-> 1618     self.report_error(f'No suitable extractor{format_field(ie_key, None, " (%s)")} found for URL {url}',
   1619                       tb=False if extractors_restricted else None)

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1092, in YoutubeDL.report_error(self, message, *args, **kwargs)
   1087 def report_error(self, message, *args, **kwargs):
   1088     """
   1089     Do the same as trouble, but prefixes the message with 'ERROR:', colored
   1090     in red if stderr is a tty file.
   1091     """
-> 1092     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)

File ~\.conda\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py:1031, in YoutubeDL.trouble(self, message, tb, is_error)
   1029     else:
   1030         exc_info = sys.exc_info()
-> 1031     raise DownloadError(message, exc_info)
   1032 self._download_retcode = 1

DownloadError: ERROR: No suitable extractor (HiAnime) found for URL https://hianime.tojavascript/:;
```

On the other hand, single episodes still work:
```
options = {
    'outtmpl': '%(series)s\\E%(episode_number)03d - %(title)s.%(ext)s',
    'writeautomaticsub': True,
    'writesubtitles': True
}

with YoutubeDL(options) as ydl:
    ydl.download('https://hianime.to/watch/one-piece-100?ep=2142')

[HiAnime] Extracting URL: https://hianime.to/watch/one-piece-100?ep=2142
[HiAnime] 100: Fetching Anime Title
[HiAnime] 100: Fetching Episode List
[HiAnime] 2142: Fetching Server IDs
[HiAnime] 2142: Getting SUB Episode Information
[HiAnime] 2142: Getting SUB Episode Formats
[HiAnime] 2142: Downloading M3U8 Information
[HiAnime] 2142: Getting DUB Episode Information
[HiAnime] 2142: Getting DUB Episode Formats
[HiAnime] 2142: Downloading M3U8 Information
[info] 2142: Downloading subtitles: en
[info] 2142: Downloading 1 format(s): SUB1080p
[info] Writing video subtitles to: One Piece\E001 - I'm Luffy! The Man Who's Gonna Be King of the Pirates!.en.vtt
[download] Destination: One Piece\E001 - I'm Luffy! The Man Who's Gonna Be King of the Pirates!.en.vtt
[download] 100% of   17.99KiB in 00:00:00 at 194.94KiB/s   
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 321
[download] Destination: One Piece\E001 - I'm Luffy! The Man Who's Gonna Be King of the Pirates!.mp4
[download] 100% of  222.56MiB in 00:01:57 at 1.89MiB/s                    
[FixupM3u8] Fixing MPEG-TS in MP4 container of "One Piece\E001 - I'm Luffy! The Man Who's Gonna Be King of the Pirates!.mp4"
```

Any help is highly appreciated!

Thanks!

**Comment by christensenr** [comment]
not sure if it's related, but i've been unable to download as well. I'm using a powershell script with this command:

[System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic') | Out-Null
$video=[Microsoft.VisualBasic.Interaction]::InputBox("Enter Video URL", "URL")
$directory = "D:\Downloads\YTDLP\%(series)s\%(episode_number)s - %(title)s.mp4"
cd D:\Tools\yt-dlp_win
.\yt-dlp.exe $video -vU --list-formats

and the error i get is:

[debug] Command-line config: ['https://hianime.to/watch/my-dress-up-darling-17930?ep=86361', '-vU', '--list-formats']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-104572-gbe43eacb7e-20211117 (setts), ffprobe N-104572-gbe43eacb7e-20211117
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: HiAnimeIE
[debug] Plugin directories: ['D:\\Tools\\yt-dlp_win\\yt-dlp-plugins\\yt-dlp-hianime-master\\yt_dlp_plugins']
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[HiAnime] Extracting URL: https://hianime.to/watch/my-dress-up-darling-17930?ep=86361
[HiAnime] 17930: Fetching Anime Title
[HiAnime] 17930: Fetching Episode List
[HiAnime] 86361: Fetching Server IDs
[HiAnime] 86361: Getting SUB Episode Information
[HiAnime] 86361: Getting SUB Episode Formats
ERROR: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "D:\Tools\yt-dlp_win\yt-dlp-plugins\yt-dlp-hianime-master\yt_dlp_plugins\extractor\hianime.py", line 84, in _real_extract
    return self._extract_episode(slug, playlist_id, episode_id, url)
  File "D:\Tools\yt-dlp_win\yt-dlp-plugins\yt-dlp-hianime-master\yt_dlp_plugins\extractor\hianime.py", line 184, in _extract_episode
    file_url = source.get('file')
AttributeError: 'str' object has no attribute 'get'

I get that for individual episodes or playlists, and i've tried several anime, all with the same error.

If i need to add anything, let me know.

Thanks

**Comment by SYFY-STORM** [comment]
Hi, I am also having the same issue.

Command: yt-dlp -vvF --list-subs https://hianime.to/watch/vermeil-in-gold-18081?ep=92598

Error:

[debug] Command-line config: ['-vvF', '--list-subs', 'https://hianime.to/watch/vermeil-in-gold-18081?ep=92598']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-40-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: HiAnimeIE, SamplePluginIE, sample (YoutubeIE)
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Plugin directories: ['/home/syfy/.local/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1832 extractors
[HiAnime] Extracting URL: https://hianime.to/watch/vermeil-in-gold-18081?ep=92598
[HiAnime] 18081: Fetching Anime Title
[HiAnime] 18081: Fetching Episode List
[HiAnime] 92598: Fetching Server IDs
[HiAnime] 92598: Getting SUB Episode Information
[HiAnime] 92598: Getting SUB Episode Formats
ERROR: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/syfy/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/syfy/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/syfy/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/syfy/.local/lib/python3.10/site-packages/yt_dlp_plugins/extractor/hianime.py", line 84, in _real_extract
    return self._extract_episode(slug, playlist_id, episode_id, url)
  File "/home/syfy/.local/lib/python3.10/site-packages/yt_dlp_plugins/extractor/hianime.py", line 184, in _extract_episode
    file_url = source.get('file')
AttributeError: 'str' object has no attribute 'get'

I have tried to fix the issue at source of _extract_episode but ended up finding more errors.

Let me know if I need to add any more.

Thanks

**Comment by pratikpatel8982** [comment]
I'll look into it.

**Comment by boxkim14** [comment]
Thanks @pratikpatel8982 to take your time to fix this,
I think the value of sources = video_data.get('sources', []) is encrypted now. I guess you need to find the secret key to decrypt it with AES.

**Comment by christensenr** [comment]
Updating what i've run into today, instead of getting an error about str not having an object, now i'm getting: 

PS C:\Tools\yt-dlp_win> .\yt-dlp_anime_get_formats.ps1
[debug] Command-line config: ['-F', 'https://hianime.to/watch/loner-life-in-another-world-19337?ep=128831', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-104572-gbe43eacb7e-20211117 (setts), ffprobe N-104572-gbe43eacb7e-20211117
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: HiAnimeIE
[debug] Plugin directories: ['C:\\Tools\\yt-dlp_win\\yt-dlp-plugins\\yt-dlp-hianime\\yt_dlp_plugins']
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[HiAnime] Extracting URL: https://hianime.to/watch/loner-life-in-another-world-19337?ep=128831
[HiAnime] 19337: Fetching Anime Title
[HiAnime] 19337: Fetching Episode List
[HiAnime] 128831: Fetching Server IDs
[HiAnime] 128831: Getting SUB Episode Information
[HiAnime] 128831: Getting SUB Episode Formats
ERROR: [HiAnime] 128831: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1790, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1849, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2856, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [HiAnime] 128831: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by matekelemen** [comment]
megacloud changed its `getSources` signature.

Here's an issue from a similar project (in JS): ghoshRitesh12/aniwatch#4. They solved it by copying [some guy's solution](https://github.com/drblgn/rabbit_wasm/blob/3ad1dec9d29affd810786faebeb78203a3aa7f83/rabbit.ts), but that looks super sketchy to me.

**Comment by SYFY-STORM** [comment]
Ran the code through chatgpt as I'm not that good at reading code but here is a run down on it.

The provided code appears to be a complex implementation with the following features and functions:

1. Environment Simulation:

It creates a "fake" window object to simulate a browser-like environment, including localStorage, navigator, and other browser properties. This is often used in environments where browser APIs are required but unavailable (e.g., Node.js).



2. WebAssembly (WASM) Integration:

The code initializes and interacts with WebAssembly modules using helper functions like initWasm. This enables high-performance operations by running compiled WebAssembly binaries.



3. Data Encoding and Decoding:

Functions like encode and decodeSub are implemented for converting text to binary data and vice versa.

Uses TextEncoder and TextDecoder for UTF-8 string processing.



4. Canvas and Image Manipulation:

Contains structures like canvas and image_data, which seem to prepare for image rendering or processing tasks.

Provides placeholders for drawing and manipulating canvas elements.



5. Custom Memory Management:

Implements a custom memory management system with functions like getMemBuff, addToStack, and shift. These manage an array arr to simulate a stack-like behavior.



6. Pseudo-Random Data Generation:

Mimics cryptographic functions for randomness, such as getRandomValues and randomFillSync.



7. Custom Utility Functions:

Includes helpers for detecting object types (__wbindgen_is_function, __wbindgen_is_string) and managing WebAssembly references (__wbindgen_object_drop_ref).



8. Data Parsing:

Provides a function parse for encoding strings into WebAssembly-compatible memory buffers.



9. WASM Exports:

Interacts with WebAssembly exports, as seen in __wbindgen_export_3, export4, etc.


This code appears to be part of a broader application that integrates WebAssembly for performance and utilizes browser-like APIs in a non-browser environment. It may be used for rendering, cryptographic operations, or even anti-detection mechanisms in automation tools.

**Comment by pratikpatel8982** [comment]
> megacloud changed its `getSources` signature.
> 
> Here's an issue from a similar project (in JS): [ghoshRitesh12/aniwatch#4](https://github.com/ghoshRitesh12/aniwatch/issues/4). They solved it by copying [some guy's solution](https://github.com/drblgn/rabbit_wasm/blob/3ad1dec9d29affd810786faebeb78203a3aa7f83/rabbit.ts), but that looks super sketchy to me.

Thanks for the info. I got it to work using the above typescript implemetation. However I am still integrating the solution into the extractor

**Comment by pratikpatel8982** [comment]
Try the new version. It works

**Comment by realSZ27** [comment]
I'm getting 403 forbidden with the new update. It still works fine in the browser, so it's weird it would give that here.

<details closed>
<summary>Full log</summary>

```powershell
PS D:\apps\yt-dlp> & '.\download anime.ps1' https://hianimez.to/watch/liz-and-the-blue-bird-278
[HiAnime] Extracting URL: https://hianimez.to/watch/liz-and-the-blue-bird-278
[HiAnime] 278: Fetching Anime Title
[HiAnime] 278: Fetching Episode List
[download] Downloading playlist: Liz and the Blue Bird
[HiAnime] Playlist Liz and the Blue Bird: Downloading 1 items of 1
[download] Downloading item 1 of 1
[HiAnime] Extracting URL: https://hianimez.to/watch/liz-and-the-blue-bird-278?ep=74983
[HiAnime] 74983: Fetching Server IDs
[HiAnime] 74983: Getting SUB Episode Information
[HiAnime] 74983: Downloading M3U8 Information
[HiAnime] 74983: Getting DUB Episode Information
[HiAnime] 74983: Downloading M3U8 Information
[info] 74983: Downloading subtitles: en
[info] 74983: Downloading 1 format(s): DUB1036p
[info] Writing video subtitles to: Full [74983].en.vtt
[download] Destination: Full [74983].en.vtt
[download] 100% of   51.00KiB in 00:00:00 at 317.86KiB/s
[SubtitlesConvertor] Converting subtitles
Deleting original file Full [74983].en.vtt (pass -k to keep)
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Finished downloading playlist: Liz and the Blue Bird
Done
```
I'm doing some remuxing in this script, but it still doesn't work without it.

</details>

**Comment by pratikpatel8982** [comment]
its a very small issue, looks like incorrect headers. will fix it soon

**Comment by pratikpatel8982** [comment]
> I'm getting 403 forbidden with the new update. It still works fine in the browser, so it's weird it would give that here.
> 
> Full log

fixed in commit eb17c8df5c3a553f54d8c7f3418c3150919719c4

**Comment by realSZ27** [comment]
Seems to work for me now. Thanks!
